stages:
  cleanup:
    cmd: python process.py
    deps:
    - dataset.csv
    - process.py
    outs:
    - processed_data.csv
  train:
    cmd: python train.py
    deps:
    - processed_data.csv
    - train.py
    metrics:
    - metrics.json
